version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: DockerFile
    command: 'python manage.py runserver 0.0.0.0:8000'
    ports:
      - 8001:8000
    volumes:
      - .:/app
    depends_on:
      - db
      
  queue:
    build:
      context: .
      dockerfile: DockerFile
    command: 'python consumer.py'
    depends_on:
      - db
      - backend

  db:
    image: mysql:8.3
    restart: always
    environment:
      MYSQL_DATABASE: 'admin'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 33067:3306

